export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOADED = "USERS_LOADED";

export const WALLET_GET_BALANCES = 'WALLET_GET_BALANCES';
export const WALLET_BALANCES_LOADING = 'WALLET_BALANCES_LOADING';
export const WALLET_BALANCES_LOADED = 'WALLET_BALANCES_LOADED';

export const WALLET_OPEN_DEPOSIT_MODAL = 'WALLET_OPEN_DEPOSIT_MODAL';
export const WALLET_CLOSE_DEPOSIT_MODAL = 'WALLET_CLOSE_DEPOSIT_MODAL';
export const WALLET_SET_DEPOSIT_MODAL_DATA = 'WALLET_SET_DEPOSIT_MODAL_DATA';
export const WALLET_OPEN_WITHDRAW_MODAL = 'WALLET_OPEN_WITHDRAW_MODAL';
export const WALLET_CLOSE_WITHDRAW_MODAL = 'WALLET_CLOSE_WITHDRAW_MODAL';
export const WALLET_SET_WITHDRAW_MODAL_DATA = 'WALLET_SET_WITHDRAW_MODAL_DATA';
